//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Subotai.Dal.Gatekeeper.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int Id { get; set; }
        public Nullable<long> IdUsers { get; set; }
        public string Number { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Owner { get; set; }
    
        public virtual User User { get; set; }
    }
}
