//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Subotai.Dal.Gatekeeper.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsSold
    {
        public int Id { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> SoldCount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<long> IdLanguages { get; set; }
        public Nullable<long> IdUser { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
