//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Subotai.Dal.Gatekeeper.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public long Id { get; set; }
        public Nullable<long> IdLanguages { get; set; }
        public Nullable<long> IdPhrases { get; set; }
        public string Translation1 { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Phras Phras { get; set; }
    }
}
